package model;

public enum EnumAlgoritmo {
    DIAGONAL,
    DIAGONALINVERTIDA,
    FILASPORCOLUMNAS,
    COLUMNASPORFILAS,
    UNAFILA,
    UNACOLUMNA,
    FILASPARES,
    FILASIMPARES,
    COLUMNASPARES,
    COLUMNASIMPARES;
}
